version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend